### ISSUE TITLE
Uncaught TYPO3 Exception: The action "unsubscribe" (controller "Log") is not allowed by this plugin

### ISSUE THREAD

**Issue by seirerman** [bihor/fp_newsletter#24] opened 2020-04-06 08:53 UTC
Using version 1.0.0 of fp_newsletter I get an error when I call the unsubscribe-link from a direct_mail newsletter (https://www.domain.com/path/to/direct/unsubscription/plugin/?u=123&t=t&a=02520bda redirecting to .../?tx_fpnewsletter_pi1%5Blog%5D=15&tx_fpnewsletter_pi1%5Berror%5D=9&tx_fpnewsletter_pi1%5Baction%5D=unsubscribe&cHash=3b46b55629894e2eb08c6bd3f9b90589):

`#1313855175: The action "unsubscribe" (controller "Log") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.`

The unsubscribe plugin is listed in the code, so I'm not sure where this is coming from.

When I open the page directly (https://www.domain.com/path/to/direct/unsubscription/plugin/), I get the error `Fehler - Der Abmelde-Link konnte nicht verarbeitet werden.` This is probably fine, since there are no parameters from the direct_mail newsletter. But it also shows that TYPO3 found the correct action/plugin.

Any idea why that is happening?

**Comment by bihor** [comment] 2020-04-07 07:59
Well, you need to specify an unsubscribeUid via TypoScript or FlexForm.
On that page you must select at the plugin "Newsletter: unsubscribe via link".
There are 2 unsubscribe possibilities, but only one unsubscribeUid .
Yes, thats tricky...

**Comment by bihor** [comment] 2020-04-07 08:02
Here you can see how to build the link for direct_mail:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/master/en-us/Administrator/Index.html
You don´t need any unsubscribeUid, because you can´t use that Uid in direct_mail.

**Comment by djangones** [comment] 2020-04-13 13:16
I can cofirm the same error with version 1.0.0
1. - `unsubscribeUid` is set correctly via typoscript (I also checked to set it via FlexForm, too)
2. - the plugin on the referenced page is set to "Newsletter: unsubscribe via link"
3. - the unsubscription url is formated like described in the manual

**Comment by jacques2017** [comment] 2020-06-18 10:06
I can confirm the same error and I take a look into the sourcecode.
On unsubscribe with the link the unsubscribeDMaction is called. Then the deleteAction.
In the deleteAction the reCaptcher-Call returns "unsucces" so that the "error" is set to 9,
In this case the unsubscribeAction is called, but this is not defined in the flexform.
Please fix this.
Why do you call the reCaptcha?
See this snippet from the Error-Message: resolveActionName('Log', array('action' => 'unsubscribe', 'error' => '9', 'log' => '15'))

**Comment by jacques2017** [comment] 2020-06-18 10:23
I added "Log->unsubscribe" to the flexform.
Now the unsubscribeAction is called. But now I get the Message: 
"Validation failed while trying to call Fixpunkt\FpNewsletter\Controller\LogController->unsubscribeAction(). "

**Comment by jacques2017** [comment] 2020-06-18 10:32
Now it works,
I activated the mathCaptcha in the unsubscirb-Flexform. This is wrong. Now I deaktivated it an now it works.

**Comment by bihor** [comment] 2020-06-18 18:46
Hello  jacques2017,
can you describe the problem in one post?
Should I add unsubscribe to the FlexForm of "unsubscribeDMaction" ?
Is the real problem something with ReCaptcha or mathCaptcha?

**Comment by jacques2017** [comment] 2020-06-19 06:43
Hello bihor,
after I deaktivated the mathCaptcha in the TYPO3-Backend on the unsubscribe-Flexform there was no error.
But it would be nice, if you could show an errormessage in the Frontend, if the error is >= 8 instead of redirecting to the unsubscribe-action.

**Comment by bihor** [comment] 2020-07-14 13:44
OK, I guess I have fixed now this error.
It occurs only when a captcha method is enabled on the direct unsubscription page.
In this case I will ignore now the captcha, when the auth-code is fine.

**Closed by bihor** 2020-07-14 13:44 UTC
